

# encrypty build
env = Environment(tools=['javac', 'jar'])

env.Java(target='classes', source='src')

env.Jar(target='bin/verify-rsa.jar', 
        source=['classes', 'VerifyManifest.txt'],
        JARCHDIR='$SOURCE')

